# Video Game Sales Intelligence Suite
## Notebook 01: Data Understanding and Cleaning

---

### 1 - Importing Libraries and Setup Environment

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

### 2 - Load Raw Data

In [2]:
# Load the raw dataset
data = pd.read_csv("../data/raw/data.csv")
data_dict = pd.read_csv("../data/raw/data_dictionary.csv")

Let's see what's the data looks like...

In [3]:
# Display the first few rows of the dataset to understand what the data looks like
print("First 5 rows of the dataset:")
data.head()

First 5 rows of the dataset:

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

Time to check out what does each column (feature) mean...

In [ ]:
# Display the data dictionary
data_dict

           Field                                     Description
0            img        URL slug for the box art at vgchartz.com
1          title                                      Game title
2        console               Console the game was released for
3          genre                               Genre of the game
4      publisher                           Publisher of the game
5      developer                           Developer of the game
6   critic_score                    Metacritic score (out of 10)
7    total_sales              Global sales of copies in millions
8       na_sales      North American sales of copies in millions
9       jp_sales            Japanese sales of copies in millions
10     pal_sales  European & African sales of copies in millions
11   other_sales       Rest of world sales of copies in millions
12  release_date                   Date the game was released on
13   last_update                  Date the data was last updated